server:
  port: 7000

spring:
  application:
    name: atguigu-crowd-pay
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.153.138
    password: 111111
  session:
    store-type: redis


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ali:
  pay:
    alipay-public-key: ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
    app-id: 9021000122699995
    charset: utf-8
    gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    merchant-private-key: ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
    notify-url: http://9xpfih.natappfree.cc/pay/notify
    return-url: http://localhost/pay/return
    sign-type: RSA2
